default_context:
  project_name: 'farmOS-aggregator'
  project_slug: 'farmOS-aggregator'
  domain_main: 'localhost'
  domain_staging: 'stag.localhost'
  docker_swarm_stack_name_main: 'localhost'
  docker_swarm_stack_name_staging: 'stag-localhost'
  secret_key: '1f034e80442f37b6cfe1e9b442ef431b73fc4b727bf94bd93ed963adb2dec58a'
  first_superuser: 'admin@localhost'
  first_superuser_password: 'test'
  backend_cors_origins: 'http://localhost, http://localhost:4200, http://localhost:3000, http://localhost:8080, https://localhost, https://localhost:4200, https://localhost:3000, https://localhost:8080, http://dev.localhost, https://stag.localhost, https://localhost, http://local.dockertoolbox.tiangolo.com, http://localhost.tiangolo.com'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@localhost'
  postgres_password: '3b7c15496ef20f1a858eecfe17e6d9147f70a13d4864d4d0b07323c72a845474'
  pgadmin_default_user: 'admin@localhost'
  pgadmin_default_user_password: 'test'
  traefik_constraint_tag: 'localhost'
  traefik_constraint_tag_staging: 'stag.localhost'
  traefik_public_network: 'traefik-public'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:test'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
