version: '3.3'
services:
  backend-tests:
    build:
      context: ./backend
      dockerfile: tests.dockerfile
    command: bash -c "while true; do sleep 1; done"
    environment:
      - SERVER_NAME=backend
      - SERVER_HOST=http://${DOMAIN}
      # Configuration for postgres DB.
      - POSTGRES_SERVER
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      # Configuration for backend app.
      - BACKEND_CORS_ORIGINS
      - SECRET_KEY
      - FIRST_SUPERUSER
      - FIRST_SUPERUSER_PASSWORD
      - SMTP_TLS
      - SMTP_PORT
      - SMTP_HOST
      - SMTP_USER
      - SMTP_PASSWORD
      - EMAILS_FROM_EMAIL
      - USERS_OPEN_REGISTRATION
      # General aggregator configuration.
      - AGGREGATOR_NAME
      - FARM_ACTIVE_AFTER_REGISTRATION
      - AGGREGATOR_OAUTH_INSECURE_TRANSPORT
      - AGGREGATOR_OPEN_FARM_REGISTRATION
      - AGGREGATOR_INVITE_FARM_REGISTRATION
      - AGGREGATOR_OAUTH_CLIENT_ID
      - AGGREGATOR_OAUTH_CLIENT_SECRET
      - AGGREGATOR_OAUTH_SCOPES
      - AGGREGATOR_OAUTH_DEFAULT_SCOPES
      - AGGREGATOR_OAUTH_REQUIRED_SCOPES
  backend:
    environment:
      # Don't send emails during testing
      - SERVER_NAME=${DOMAIN}
      - SERVER_HOST=http://${DOMAIN}
      - SMTP_HOST=
